baseURL = 'https://gordins.github.io/tw/'
languageCode = 'en-us'
title = 'TW'
theme = 'hugo-theme-learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/gordins/tw/tree/main/content/"
  author = "Ştefan Gordîn"
  description = "TW"
  showVisitedLinks = true
  disableSearch = false
  disableBreadcrumb = false
  themeVariant = "blue"
  disableLandingPageButton = true
  disableNextPrev = true
  labOne = "prezentare_gordin_01.pdf"

